Repository kubewharf/katalyst-api, pull requests merged in 2023-07, with the labels that each got.

#18 refactor adminqos definition list and map member remove omitempty json flag
  config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml
  pkg/apis/config/v1alpha1/adminqos.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: workflow/merge-ready, chore

#19 add resource_identifier resource annotation key
  go.mod
  go.sum
  pkg/consts/resource.go
Labels: enhancement

#21 feat(eviction): system pressure eviction use duration instead of time…
  config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml
  pkg/apis/config/v1alpha1/adminqos.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, workflow/need-review

#22 feat(cgroup): add cgroup version constant variables
  pkg/consts/cgroup.go
Labels: workflow/merge-ready

#23 feat(kcnr): add utils to generate topology policy
  pkg/utils/topology_policy.go
Labels: enhancement, workflow/merge-ready, workflow/need-review

#24 refactor(api): make the resources of kcnr status optional
  config/crd/bases/node.katalyst.kubewharf.io_customnoderesources.yaml
  pkg/apis/node/v1alpha1/types.go
Labels: enhancement, workflow/merge-ready

#25 add pod-level metric pod usage
  pkg/metric/pod/pod.go
Labels: enhancement, workflow/merge-ready, workflow/need-review

#20 feat(eviction): load eviction support dynamic threshold
  config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml
  pkg/apis/config/v1alpha1/adminqos.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, workflow/need-review

#27 refactor(qrm): keep naming style in line with existing field
  config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml
  pkg/apis/config/v1alpha1/adminqos.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: workflow/need-review

#26 add more name names for kcmas
  pkg/metric/node/node.go
  pkg/metric/pod/pod.go
Labels: workflow/merge-ready, workflow/need-review
