Repository kubewharf/katalyst-api, pull requests merged in 2023-11, with the labels that each got.

#46 add spd baseline related const
  pkg/consts/spd.go
  pkg/utils/topology_policy.go
Labels: workflow/merge-ready, workflow/need-review

#51 add detailed comments for katalyst enhancements and other consts
  pkg/consts/overcommit.go
  pkg/consts/qos.go
  pkg/consts/spd.go
  pkg/consts/vpa.go
Labels: workflow/merge-ready, workflow/need-review

#49 feat(qrm): Support for OOM priority as a QoS enhancement
  pkg/consts/qos.go
  pkg/consts/qrm.go
Labels: workflow/need-review

#52 rename baselineRatio to baselinePercent
  config/crd/bases/workload.katalyst.kubewharf.io_serviceprofiledescriptors.yaml
  pkg/apis/workload/v1alpha1/types.go
  pkg/apis/workload/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: enhancement, workflow/need-review

#50 feat(tide): support tide nodepool
  config/crd/bases/tide.katalyst.kubewharf.io_tidenodepools.yaml
  hack/update-codegen.sh
  pkg/apis/tide/v1alpha1/doc.go
  pkg/apis/tide/v1alpha1/register.go
  pkg/apis/tide/v1alpha1/types.go
  pkg/apis/tide/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/fake/fake_tide_client.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/fake/fake_tidenodepool.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/tide_client.go
  pkg/client/clientset/versioned/typed/tide/v1alpha1/tidenodepool.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/tide/interface.go
  pkg/client/informers/externalversions/tide/v1alpha1/interface.go
  pkg/client/informers/externalversions/tide/v1alpha1/tidenodepool.go
  pkg/client/listers/tide/v1alpha1/expansion_generated.go
  pkg/client/listers/tide/v1alpha1/tidenodepool.go
  pkg/protocol/evictionplugin/v1alpha1/api.pb.go
  pkg/protocol/reporterplugin/v1alpha1/api.pb.go
Labels: enhancement
