Repository kubewharf/katalyst-api, pull requests merged in 2023-06, with the labels that each got.

#14 chore(*): add some open-source infra config
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/status-check.yml
  Makefile
Labels: workflow/need-review, chore

#13 refactor(*): merge all EvictionConfiguration fields to AdminQoSConfiguration
  config/crd/bases/config.katalyst.kubewharf.io_adminqosconfigurations.yaml
  config/crd/bases/config.katalyst.kubewharf.io_evictionconfigurations.yaml
  pkg/apis/config/v1alpha1/adminqos.go
  pkg/apis/config/v1alpha1/eviction.go
  pkg/apis/config/v1alpha1/register.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
Labels: workflow/merge-ready, refactor

#15 feat(api): add values of topology policy to kcnr
  pkg/apis/node/v1alpha1/types.go
Labels: enhancement, workflow/merge-ready, workflow/need-review

#16 feat(api): add siblings to topology zone in kcnr
  config/crd/bases/node.katalyst.kubewharf.io_customnoderesources.yaml
  pkg/apis/node/v1alpha1/types.go
  pkg/apis/node/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: enhancement, workflow/merge-ready, workflow/need-review
