Repository kubewharf/katalyst-api, pull requests merged in 2024-02, with the labels that each got.

#63 feat(kcnr): add node metric
  config/crd/bases/node.katalyst.kubewharf.io_customnoderesources.yaml
  pkg/apis/node/v1alpha1/types.go
  pkg/apis/node/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, workflow/merge-ready

#64 rename target indicator name to service system indicator name
  pkg/apis/workload/v1alpha1/types.go
Labels: workflow/need-review, chore

#67 remove useless dependency for spd
  pkg/apis/workload/v1alpha1/types.go
  pkg/protocol/evictionplugin/v1alpha1/api.pb.go
  pkg/protocol/reporterplugin/v1alpha1/api.pb.go
Labels: workflow/merge-ready, refactor
